sudo: required
language: csharp
mono: none
dist: xenial
dotnet: 2.2.105

cache:
  directories:
    - $HOME/.cache/yarn
    - $HOME/.nuget
    - $HOME/.local/share/NuGet

env:
  - FAKE_DETAILED_ERRORS=true

services:
  - docker

jobs:
  include:
    - stage: build
      if: tag =~ ^\d+\.\d+\.\d+-[a-zA-Z0-9.]+$
      script: docker build -t hkccr.ccs.tencentyun.com/zeeko/blog-server:tmp --build-arg APPENV=Production .
      deploy:
        - provider: script
          script: ./fake.sh build -t $TRAVIS_TAG -n hkccr.ccs.tencentyun.com/zeeko/blog-server -l
          on:
            tags: true
