sudo: required
language: csharp
mono: none
dist: xenial
dotnet: 2.2.204

before_install: 
  - export PATH=$PATH:$HOME/.dotnet/tools
  - dotnet tool install -g paket

cache:
  directories:
    - $HOME/.cache/yarn
    - $HOME/.local/share/NuGet/Cache
    - $HOME/.nuget/packages

env:
  - FAKE_DETAILED_ERRORS=true

services:
  - docker

jobs:
  include:
    - stage: build
      if: tag =~ ^\d+\.\d+\.\d+-[a-zA-Z0-9.]+$
      script: ./fake.sh build -t publish
      deploy:
        - provider: script
          script: ./fake.sh build -t docker:publish -- -t $TRAVIS_TAG -n hkccr.ccs.tencentyun.com/zeeko/blog-server -l
          on:
            tags: true
